export namespace locationStoreEnum {
  export enum Getters {
    GET_PROVINCES = 'GET_PROVINCES',
    GET_REGENCIES = 'GET_REGENCIES',
    GET_DISTRICTS = 'GET_DISTRICTS',
    GET_VILLAGES = 'GET_VILLAGES'
  }
  export enum Mutations {
    SET_PROVINCES = 'SET_PROCINCES',
    SET_REGENCIES = 'SET_REGENCIES',
    SET_DISTRICTS = 'SET_DISTRICTS',
    SET_VILLAGES = 'SET_VILLAGES'
  }

  export enum Actions {
    FETCH_PROVINCES = 'FETCH_PROVINCES',
    FETCH_REGENCIES = 'FETCH_REGENCIES',
    FETCH_DISTRICTS = 'FETCH_DISTRICTS',
    FETCH_VILLAGES = 'FETCH_VILLAGES'
  }
}
